export enum TestId {
    MalformedLogMsg = 'malformed-log-msg',
    SigningLogMsg = 'signing-log-msg',
    IssuerLogMsg = 'issuer-log-msg',
    ExpirationLogMsg = 'expiration-log-msg',
    RevocationLogMsg = 'revocation-log-msg',
    SuspensionLogMsg = 'suspension-log-msg',
    GeneralErrorMsg = 'general-error-msg',
    UnknownErrorMsg = 'unknown-error-msg',
    SigningErrorMsg = 'signing-error-msg',
    MalformedErrorMsg = 'malformed-error-msg',
    ResultLog = "result-log",
    IssuedTo = "issued-to",
    IssuanceDate = "issuance-date",
    ExpirationDate = "expiration-date",
    CredentialDescription = "credential-description",
    CredentialCriteria = "credential-criteria",
    CredentialName="credential-name",
    AchievementType="achievement-type",
    AchievementImage="achievement-image"
}